### ISSUE TITLE
i think i broke it

### ISSUE THREAD

**Issue by draculonnie** [MiniDiscordThemes/Pesterchum#2]
yeah i dont even know how to describe this
i literally dont know whats happening
![image](https://github.com/MiniDiscordThemes/Pesterchum/assets/165244770/339efcf9-dd3c-409b-87d9-5679fb4c84aa)

**Comment by TheScammingFox** [comment]
Dealing with the same issues, the colors have stayed but the 'boxes' that formed up most of the theme aside from the squared icons and pfps are not working.

**Comment by Radiational** [comment]
same thing here, stopped displaying properly this morning when i opened discord. no idea what happened

**Comment by Radiational** [comment]
oh it just got updated, neat! although it appears the issue just fixed itself before i got to update it, perhaps it was some server issue or something
hope it works for you all too
